{
    'name': 'Module Bundle',
    'version': '1.0.0',
    'author': 'Mamba Tech',
    'category': 'Tools',
    'summary': 'Installs core Odoo apps',
    'depends': [
        "account_reconcile_oca",
        "accounting_pdf_reports",
        "om_account_asset",
        "om_account_budget",
        "om_fiscal_year",
        "om_recurring_payments",
        "om_account_daily_reports",
        "om_account_followup",
        "om_account_accountant",
        "muk_web_theme",
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}